### PR TITLE
Suggestion: Using StrongName instead

### PR DESCRIPTION
**Pull request by Tazer**
Should this be done ? 

The problem is with: http://blogs.msdn.com/b/webdev/archive/2014/05/12/announcing-asp-net-session-state-provider-for-redis-preview-release.aspx also made an issue here: https://github.com/StackExchange/StackExchange.Redis/issues/146

### CODE REVIEW

**Comment by TheCloudlessSky** [comment]
Thanks for bringing this to my attention!

I don't want to maintain *two* separate Nuget releases because it's a hack (and confuses people). Even though I'm personally against strong naming (it should be deprecated all together), what should happen is StackExchange.Redis should *not* have two separate packages (because it causes problems like this). It forces every library that has a dependency on StackExchange.Redis to *also* have two separate libraries. If the library wants to support strong naming, it should just be [a single library with a frozen assembly version](https://github.com/octokit/octokit.net/issues/405#issuecomment-41205847). I'll leave this open and continue the discussion on StackExchange/StackExchange.Redis#146.

**Comment by TheCloudlessSky** [comment]
@Tazer I'm sure you're getting updates on the other issue, but right now without having to rebuild/change any projects, you can do the following in your project.

1. Right-click on the `StackExchange.Redis.StrongName` reference in your project(s) and click on **Properties**.
2. Change the **Aliases** to `signed` (remove `global`):

image

Because you don't need to use StackExchange.Redis directly when you configure Microsoft.Web.RedisSessionStateProvider, you can change its alias to anything other than `global` and this allows the project to compile/run. I just tested this with a fresh MVC4 project and it worked perfectly.

**Comment by Tazer** [comment]
Great, Thanks for the update. I did solve it in the meantime with a custom built version with StackExchange.Redis.StrongName as a Reference, But will use your suggestion when I have some time over

**Comment by Tazer** [comment]
But guess your comment would be great to have in the README.md ? :)

**Comment by TheCloudlessSky** [comment]
Yup - I've added a link back to this PR in the README. Thanks!

**Comment by dobryanskyy** [comment]
I have to use strong naming due to policy in my company. To be able to use this library i had to compile sources with my own key(as well as redis lib). Now i will not be able to use updates from this lib('cause they will not appear in my nuget and i'll miss them). Such a pity....

**Comment by TheCloudlessSky** [comment]
@dobryanskyy Your company needs to review it's policy because [strong naming is not guaranteed and is not recommended for sandboxing anymore]((https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i).

If you submit a PR that automatically does the strong naming, I'd be happy to include it for those that need it.

**Comment by TheCloudlessSky** [comment]
@dobryanskyy Have you seen this: https://github.com/dsplaisted/strongnamer

**Comment by dobryanskyy** [comment]
Yes, I've seen that. I even tried it. But for some reason - it crashed upon working on this package.

**Pull request closed without merging**
